name: Deploy Front-end (Static Site → S3 + CloudFront)

on:
  push:
    # only run when front-end files change
    branches: [main]
    paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.js"
      - "src/**"
      - "public/**"
      - ".github/workflows/**"
      - "index.html"
      - "error.html"
      - "script.js"
      - "style.css"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g. us-east-1

      - name: Debug list repository contents
        run: |
          echo "PWD: $(pwd)"
          echo ""
          echo "--- repo root contents ---"
          ls -la
          echo ""
          echo "--- key files check ---"
          ls -la index.html styles.css script.js public/ || echo "Some files missing"

      - name: Sync frontend files to S3
        run: |
          aws s3 sync . s3://vibebycory-resume-content \
           --delete \
           --cache-control "no-cache" \
           --exclude "*" \
           --include "index.html" \
           --include "error.html" \
           --include "styles.css" \
           --include "script.js" \
           --include "public/*" \
           --include "*.pdf" \
           --include "*.png" \
           --include "*.jpg" \
           --include "*.jpeg" \
           --include "*.gif" \
           --include "*.ico"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"
